global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    datacenter: 'kossev-dc'
    cluster: 'prod'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 15s
    static_configs:
      - targets:
          - nodeexporter-1blu-16R-vm:9100
          - kossev-it-berater.com
          - mail.kossev-it-berater.com

  - job_name: 'wordpress'
    scrape_interval: 15s
    metrics_path: /wp-json/metrics
    static_configs:
      - targets:
          - www.kossev-it-berater.com
          - www.simplylovelychaos.de
          - www.kabbalisten.de
          - www.kabbala-ru.de
          - sohar.kabbalisten.de
          - tora.kabbalisten.de

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'cadvisor-web'
    scrape_interval: 15s
    metrics_path: /cd-metrics
    static_configs:
      - targets: ['www.kossev-it-berater.com']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'nginx'
    scrape_interval: 10s
    static_configs:
      - targets: ['nginxexporter:9113']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
